quarkus.smallrye-openapi.a.info-title=a
quarkus.smallrye-openapi.b.info-title=b
quarkus.smallrye-openapi.1.info-title=b
quarkus.smallrye-openapi.2.info-title=b
quarkus.smallrye-openapi.3.info-title=b
quarkus.smallrye-openapi.4.info-title=b
quarkus.smallrye-openapi.5.info-title=b
quarkus.smallrye-openapi.6.info-title=b
quarkus.smallrye-openapi.7.info-title=b
quarkus.smallrye-openapi.8.info-title=b
quarkus.smallrye-openapi.9.info-title=b
quarkus.smallrye-openapi.10.info-title=b
quarkus.smallrye-openapi.11.info-title=b
quarkus.smallrye-openapi.12.info-title=b
quarkus.smallrye-openapi.13.info-title=b
quarkus.smallrye-openapi.14.info-title=b
quarkus.smallrye-openapi.15.info-title=b
quarkus.smallrye-openapi.16.info-title=b
quarkus.smallrye-openapi.17.info-title=b
quarkus.smallrye-openapi.18.info-title=b
quarkus.smallrye-openapi.19.info-title=b
quarkus.smallrye-openapi.20.info-title=b
